### ISSUE TITLE
Cannot download the dataset

### ISSUE THREAD

**Issue by rann1018** [lzx551402/GL3D#3]
Hi 

Thanks a lot for your work and the dataset.

However, when I download the dataset following your instructions:
`bash download_data.sh gl3d_imgs 0 125`
The error shows:
 wget: 无法解析主机地址 “research.altizure.com”

Is there any trouble with this website?
Looking forward to your reply.

**Comment by lzx551402** [comment]
Hi,

I just tried the command you provided, and the downloading works for me. I would suggest you switching to different network and find the one that can ping research.altizure.com. I suspect that our web domain is somehow blocked by your network (university/company).

**Comment by rann1018** [comment]
Hi,

Thanks a lot for your help!

I have successfully downloaded your dataset. However, I found there were some problems. 

When I downloaded gl3d_imgs, I found there were only 339 scenes. When I downloaded gl3d_ct and gl3d_mo, I found there were 543 scenes. The number of these two datasets is not equal.

I do not know if there are some mistakes with my process.
Looking forward to your reply.

**Comment by lzx551402** [comment]
Hi,

I verified all downloadings last week, and I didn't encounter the problem you reported. You may have noticed that we have provided the sha1sum, so you may compare it so as to check the completeness of your downloading.

**Comment by lzx551402** [comment]
I will close this issue due to the lack of activity.
