### ISSUE TITLE
Full resolution dataset

### ISSUE THREAD

**Issue by rjanvier** [lzx551402/GL3D#4]
Hello, thanks for making this benchmark and dataset public.
I'm a bit old school here, but do you think it would be possible to make the full res dataset public (4000x3000 images) to benchmark handcrafted methods against GL3D?
thanks!

**Comment by lzx551402** [comment]
Sorry for the late reply. Due to the size limit, I currently uploaded the raw images of [test set](https://github.com/lzx551402/GL3D/blob/v2/list/gl3d/imageset_test.txt) in GL3D (40 scenes), which can be accessed by 

> bash download_data.sh gl3d_raw_imgs 0 106

I will try to upload the full dataset in the next week.

**Comment by rjanvier** [comment]
Hey,
my bad, it was exactly what I was looking for! Maybe i could be more explicitly stated in the README.
`~4000 x 3000 raw images of test set of GL3D `
Anyway, thank you very much.
