### ISSUE TITLE
How to get patches?

### ISSUE THREAD

**Issue by KarlThelor** [lzx551402/GL3D#6]
Since the keypoints are detected from distorted images,how to get patches from undistort images ?

**Comment by lzx551402** [comment]
it is indeed a bit troublesome, you may first refer to this [example](https://github.com/lzx551402/GL3D/blob/v2/example/visualize.py#L168) for point undistortion. I will write another example to address your concern.

**Comment by KarlThelor** [comment]
Much obliged,that would be great helpful

**Comment by Archaon6734** [comment]
Your work are great，but I have a similar problem,we can get the keypoint location in undistort images just as example "(x, y) = (TRANSFORMATION[0, 2] * W/2 + W/2, TRANSFORMATION[1, 2] * H/2 + H/2)"
what's the meaning of TRANSFORMATION[0, 0],and TRANSFORMATION[0, 1]?
If they are the reslut of  transformation in GeoDesc 3.2,and if I want get the correnspond patch in differnt scale image,it seems like that I need  solve  a trigonometric equation to get scale (σ) and orientation (θ) parameters of SIFT.

**Comment by lzx551402** [comment]
@KarlThelor @Archaon6734 Hi two, thank you for your concerning. I write an [example](https://github.com/lzx551402/GL3D/blob/v2/example/visualize.py) to address your concerns, you may now call ``python visualize.py patch`` to extract the matching patches.  You will be able to see something like [this](https://github.com/lzx551402/GL3D/blob/v2/imgs/example_patch.png).

I think this fragment of code would better explain your questions.

**Comment by Archaon6734** [comment]
It really solved my troubles，I really appreciate your help，thanks!
